apiVersion: velero.io/v1
kind: Backup
metadata:
  namespace: openshift-adp
  name: mssql-persistent-backup
spec:
  defaultVolumesToRestic: true
  includeClusterResources: true
  includedNamespaces:
    - mssql-persistent
  storageLocation: dpa-sample-1
  ttl: 720h0m0s
